DROP TABLE IF EXISTS PEDIDO;

CREATE TABLE PEDIDO
(
    pedid                       integer        NOT NULL,
    peddata                     date,
    priid                       varchar(32),
    pedfi                       varchar(128)   NOT NULL,
    pedseed                     varchar(10),
    spedid                      integer,
    estpin1                     integer,
    usuid                       integer        NOT NULL,
    pfscpf                      integer        NOT NULL default 0,
    pfsnome                     varchar(64),
    pfsemail                    varchar(128),
    pfsendereco                 varchar(128),
    pfscomplemento              varchar(128),
    pfsbairro                   varchar(128),
    pfsmunicipio                varchar(64),
    pfsuf                       char(2),
    pfspais                     varchar(128),
    pfscep                      integer,
    pfstelefone                 integer,
    pfsdtnascimento             date,
    pfspis                      integer,
    pfsrg                       varchar(16),
    pfsrgemissor                varchar(10),
    pfsrfuf                     char(2),
    pfstiteleit                 integer,
    pfstiteleitzona             integer,
    pfstiteleitsecao            integer,
    pfstitmunicipio             varchar(128),
    pfstiteleituf               char(2),
    pfsprofissao                varchar(128),
    prdou1                      varchar(128),
    prdout2                     varchar(128),
    prdout3                     varchar(128)            default '',
    prdout4                     varchar(128)            default '',
    prdout5                     varchar(128)            default '',
    pjrcnpj                     integer,
    pjrracaosocial              varchar(128),
    orid                        integer,
    grpid                       char(5),
    arid                        char(5),
    orcodigo                    varchar(32),
    pedbemailhtml               decimal(1, 0),
    pedbemailassinado           decimal(1, 0),
    pednumcartao                varchar(20),
    pednumrenovacao             decimal(2, 0)  NOT NULL default 0,
    pfscei                      decimal(12, 0),
    prjcei                      decimal(12, 0),
    pedvalor                    integer,
    pedintegrado                decimal(38, 0) NOT NULL default 0,
    data_pgto                   date,
    pedbloqueiodata             integer,
    numtentativas               integer,
    pedtipoemissao              varchar(10),
    pedtipovalidacao            varchar(10)             default '',
    datanotificacao             decimal(38, 0),
    cd_mov_cliente              varchar(16),
    cd_envio_email_ped_corp     integer,
    ic_bloqueio_fraude          integer,
    ic_analise_seguranca        integer,
    ic_termo_biometria          integer,
    ic_apto_verif_otimi         decimal(1, 0),
    ic_doc_pendente             decimal(1, 0)  NOT NULL,
    ic_biometria_pedido         decimal(1, 0),
    ic_renovacao_concorrente    decimal(1, 0)  NOT NULL,
    nm_ac_certificado_renovacao varchar(124),
    cert_renovacao_ac_concor    text,

PRIMARY KEY(pedid)

);